### PR TITLE
use COGReader/STACReader from rio-tiler 2.0b1

### PR DESCRIPTION
**Pull request by vincentsarago**

### CODE REVIEW

**Comment by vincentsarago** [comment]
mypy is not happy with 


https://github.com/cogeotiff/rio-tiler-crs/blob/7e04ce59c3102346c3cad9901fbd7c273b196c52/rio_tiler_crs/cogeo.py#L188

complaining that COGReader get's tms twice: `error: "COGReader" gets multiple values for keyword argument "tms`

I guess `dataclass` inheritence doesn't work as I though 

any idea @geospatial-jeff ?

**Comment by kylebarron** [comment]
Should this still be beta while `rio-tiler` is in beta?

**Comment by vincentsarago** [comment]
@kylebarron I'm fine doing a pre release for this ;-)

**Comment by geospatial-jeff** [comment]
@vincentsarago I think https://github.com/python/mypy/issues/7657 may be related

**Pull request merged**
